name = "quickplay"
compatibility_date = "2026-09-01"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "quickplay-scores"
database_id = "8d9f8bdb-ec04-4467-a929-ba212ac805eb"
